In [4]:
#Below data is imported by api method of National Oceanic and atmospheric centre(NOAA)

#needed to make web requests
import requests

#store the data we get as a dataframe
import pandas as pd

#convert the response as a strcuctured json
import json

#mathematical operations on lists
import numpy as np

#parse the datetimes we get from NOAA
from datetime import datetime

#add the access token you got from NOAA
Token = 'IxtbhcqrnRffhyuYOUdCZdirYpNZmuGV'

#Long Beach Airport station
station_id = 'GHCND:USW00023129'


#initialize lists to store data
dates_temp = []
dates_prcp = []
temps = []
prcp = []



#for each year from 2015-2019 ...

for year in range(2015, 2020):

    year = str(year)

    print('working on year '+year)

    

    #make the api call

    r = requests.get('https://www.ncdc.noaa.gov/cdo-web/api/v2/data?datasetid=GHCND&datatypeid=TAVG&limit=1000&stationid=GHCND:USW00023129&startdate='+year+'-01-01&enddate='+year+'-12-31', headers={'token':Token})

    #load the api response as a json

    d = json.loads(r.text)

    #get all items in the response which are average temperature readings

    avg_temps = [item for item in d['results'] if item['datatype']=='TAVG']

    #get the date field from all average temperature readings

    dates_temp += [item['date'] for item in avg_temps]

    #get the actual average temperature from all average temperature readings

    temps += [item['value'] for item in avg_temps]
    
    
 #initialize dataframe

df_temp = pd.DataFrame()



#populate date and average temperature fields (cast string date to datetime and convert temperature from tenths of Celsius to Fahrenheit)

df_temp['date'] = [datetime.strptime(d, "%Y-%m-%dT%H:%M:%S") for d in dates_temp]

df_temp['avgTemp'] = [float(v)/10.0*1.8 + 32 for v in temps]
df_temp

working on year 2015
working on year 2016
working on year 2017
working on year 2018
working on year 2019

           date  avgTemp
0    2015-01-01    46.58
1    2015-01-02    48.02
2    2015-01-03    49.82
3    2015-01-04    52.16
4    2015-01-05    58.64
...         ...      ...
1821 2019-12-27    49.10
1822 2019-12-28    50.90
1823 2019-12-29    51.26
1824 2019-12-30    54.68
1825 2019-12-31    58.46

[1826 rows x 2 columns]